#------------------ System Setting --------------#
broker: IB # IB CTP SINA, GOOGLE, PAPER
msgq: nanomsg           # nanomsg kafka, zmq
log_dir: d:/workspace/elitequant_cpp/log
data_dir: d:/workspace/elitequant_cpp/data
#------------------ End of System ---------------#
#-------------- Interactive Brokers -------------#
account: DU15183
ibport: 7497
# ----------------- End of IB  ------------------#
#----------------- Ctp --------------------------#
ctp_broker_id: 9999
ctp_user_id: simnow
ctp_password: simnow
ctp_md_address: tcp://180.168.146.187:10010
ctp_td_address: tcp://180.168.146.187:10000
# ---------------- End of CTP  ------------------#
tickers:
  # - IC1712
  # - IC1801
  # - IC1803
  # - IF1712
  # - IF1801
  # - al1712
  # - al1801
  # - cu1712
  # - cu1801
  - SPY STK SMART
  - AAPL STK SMART
  - AMZN STK SMART
  - TSLA STK SMART
  - GOOGL STK SMART
  - FB STK SMART
  - BIDU STK SMART
  - BABA STK SMART
  - GS STK SMART
  - JPM STK SMART
  - ESZ7 FUT GLOBEX 50
  - EUR.USD CASH IDEALPRO
  - GBP.USD CASH IDEALPRO
  #- sh600028
  #- sh601857
  #- sh600036
  #- sh601668
  #- sh601988
  #- sh601166
  #- sh601377
  #- sh600958
  